# 服务端口
server.port: 1111

#日志输出级别
logging.level.com.asiaInfo: INFO

#生产配置文件
#Dspring.config.location=/app/IBM/wuxwTest/application-dev.properties



#数据源1（多数据源配置）
spring.datasource.primary.driver-class-name: oracle.jdbc.driver.OracleDriver
spring.datasource.primary.url: jdbc:oracle:thin:@(DESCRIPTION =(ADDRESS = (PROTOCOL = TCP)(HOST = 10.128.91.100)(PORT = 1521))(ADDRESS = (PROTOCOL = TCP)(HOST = 10.128.91.101)(PORT = 1521))(LOAD_BALANCE = NO)(CONNECT_DATA =(SERVER = DEDICATED)(SERVICE_NAME = testdb)))
spring.datasource.primary.username: crm_app_1
spring.datasource.primary.password: crm_app_1

#数据源2（多数据源配置）
spring.datasource.secondary.driver-class-name: oracle.jdbc.driver.OracleDriver
spring.datasource.secondary.url: jdbc:oracle:thin:@(DESCRIPTION =(ADDRESS = (PROTOCOL = TCP)(HOST = 10.128.91.100)(PORT = 1521))(ADDRESS = (PROTOCOL = TCP)(HOST = 10.128.91.101)(PORT = 1521))(LOAD_BALANCE = NO)(CONNECT_DATA =(SERVER = DEDICATED)(SERVICE_NAME = testdb)))
spring.datasource.secondary.username: crm_app_2
spring.datasource.secondary.password: crm_app_2